name: Exo 3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask app
      run: |
        python app.py &  
        sleep 5  
        curl -X GET http://127.0.0.1:5000/ 
  
    - name: Stop Flask app
      run: |
        pkill -f "python app.py" 